name: Sync Upstream
 # sync with origin repo/main branch
on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: 'https://github.com/jrlasak/databricks-code-practice'
          upstream_sync_branch: 'main'
          target_sync_branch: 'main'
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}   
